[project]
name = "phlash"
version = "0.1.0"
description = "Bayesian inference of population history from recombining sequence data."
authors = [
    {name = "Jonathan Terhorst", email = "jonth@umich.edu"},
]
dependencies = [
    "blackjax<2.0.0,>=1.1.0",
    "cuda-python<13,>=12",
    "cyvcf2<1.0.0,>=0.30.28",
    "intervaltree<4.0.0,>=3.1.0",
    "jax!=0.4.21,!=0.4.22,!=0.4.23,<1.0.0,>=0.4.20",
    "jaxlib[cuda12_pip]!=0.4.21,!=0.4.22,!=0.4.23,<1.0.0,>=0.4.20",
    "joblib<2.0.0,>=1.3.2",
    "loguru<1.0.0,>=0.7.2",
    "matplotlib<4.0.0,>=3.8.2",
    "msprime<2.0.0,>=1.3.0",
    "numpy<2.0.0,>=1.26.3",
    "optax<1.0.0,>=0.1.9",
    "plotly<6.0.0,>=5.18.0",
    "scipy<2.0.0,>=1.12.0",
    "stdpopsim<1.0.0,>=0.2.0",
    "tqdm<5.0.0,>=4.66.1",
    "tskit<1.0.0,>=0.5.6",
    "demes<1.0.0,>=0.2.3",
    "jax-dataclasses<2.0.0,>=1.6.0",
    "sh<3.0.0,>=2.0.6",
    "tszip<1.0.0,>=0.2.3",
    "jaxtyping<1.0.0,>=0.2.25",
]
requires-python = ">=3.10,<4.0"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm]
distribution = false

[tool.pdm.build]
includes = []

[[tool.pdm.source]]
name = "jax"
url = "https://storage.googleapis.com/jax-releases/jax_releases.html"
verify_ssl = true

[tool.isort]
profile = "black"
known_first_party = "phlash"

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = true
envlist = py310,py311

[testenv]
deps =
    pytest
commands =
    pytest tests/ --import-mode importlib
"""
